# Unschemed:
FEWNERD_COARSE_LABELS = ["O", "art", "building", "event", "location", "organization", "other", "person", "product"]
# IOB/IOB2:
CONLL_LABELS = ["O", "B-PER", "I-PER", "B-ORG", "I-ORG", "B-LOC", "I-LOC", "B-MISC", "I-MISC"]
# BILOU
BILOU_CONLL_LABELS = [
    "O",
    "B-PER",
    "I-PER",
    "L-PER",
    "U-PER",
    "B-ORG",
    "I-ORG",
    "L-ORG",
    "U-ORG",
    "B-LOC",
    "I-LOC",
    "L-LOC",
    "U-LOC",
    "B-MISC",
    "I-MISC",
    "L-MISC",
    "U-MISC",
]
# BIOES
FABNER_LABELS = [
    "O",
    "B-MATE",
    "I-MATE",
    "E-MATE",
    "S-MATE",
    "B-MANP",
    "I-MANP",
    "E-MANP",
    "S-MANP",
    "B-MACEQ",
    "I-MACEQ",
    "E-MACEQ",
    "S-MACEQ",
    "B-APPL",
    "I-APPL",
    "E-APPL",
    "S-APPL",
    "B-FEAT",
    "I-FEAT",
    "E-FEAT",
    "S-FEAT",
    "B-PRO",
    "I-PRO",
    "E-PRO",
    "S-PRO",
    "B-CHAR",
    "I-CHAR",
    "E-CHAR",
    "S-CHAR",
    "B-PARA",
    "I-PARA",
    "E-PARA",
    "S-PARA",
    "B-ENAT",
    "I-ENAT",
    "E-ENAT",
    "S-ENAT",
    "B-CONPRI",
    "I-CONPRI",
    "E-CONPRI",
    "S-CONPRI",
    "B-MANS",
    "I-MANS",
    "E-MANS",
    "S-MANS",
    "B-BIOP",
    "I-BIOP",
    "E-BIOP",
    "S-BIOP",
]
